name: build_sample_plugins
on: [push]
jobs:
  build:
    strategy: 
      matrix:
        runs-on: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          submodules: true
      - name : "Build plugins"
        run: |
          cd iolite_c_api/sample_plugins
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
      - name : "Archive plugins"
        uses: actions/upload-artifact@v4
        with:
          name: sample_plugins-${{ matrix.runs-on }}
          path: |
            iolite_c_api/sample_plugins/linux/*.so
            iolite_c_api/sample_plugins/windows/*.dll
  merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Download artifacts" 
        uses: actions/download-artifact@v4
        with:
          path: sample_plugins 
          pattern: sample_plugins-*
          merge-multiple: true
      - name : "Archive plugins"
        uses: actions/upload-artifact@v4
        with:
          name: sample_plugins
          path: |
            sample_plugins/**/*